{
 "title": "Climate and HVAC",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "period",
    "label": "Usage Period",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Outdoor Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_temperature_celsius{friendly_name=\"PirateWeather Temperature\"}"
    }
   ]
  },
  {
   "title": "Inside Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_climate_current_temperature_celsius{friendly_name=\"Main Floor Thermostat\",job=\"hass\"}"
    }
   ]
  },
  {
   "title": "Today's Rain",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "hass_sensor_unit_in{entity=\"sensor.pirateweather_precip_intensity\",job=\"hass\"}"
    }
   ]
  },
  {
   "title": "Indoor/Outdoor Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_humidity_percent{friendly_name=\"Main Floor Thermostat Humidity\",job=\"hass\"}"
    },
    {
     "expr": "hass_sensor_humidity_percent{friendly_name=\"PirateWeather Humidity\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_unit_uvu0x20index{friendly_name=\"PirateWeather UV Index\",job=\"hass\"}"
    }
   ]
  },
  {
   "title": "Motion & Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg by (action) (hass_climate_action{friendly_name=\"Main Floor Thermostat\",job=\"hass\"})",
     "legendFormat": "{{action}}"
    },
    {
     "expr": "avg by (friendly_name) (hass_binary_sensor_state{friendly_name=~\"Main Floor Thermostat Occupancy|Master Bedroom Sensor Occupancy\"})",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(hass_sensor_temperature_celsius{friendly_name=~\"Back Patio Hose Bib Crawl Space Climate Probe Temperature|Broadlink Hub Temperature|Dog Run Hose Bib Crawl Space Probe Temperature|Garage Motion Sensor Temperature|Laundry Room Motion Temperature|Main Floor Thermostat Temperature|Master Bedroom Closet Motion Temperature|Master Bedroom Sensor Temperature|Office Closet In-Wall Climate Probe Temperature|Office Side Crawl Space Climate Probe Temperature\"}) * 1.8 + 32",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Outside Temps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "hass_sensor_temperature_celsius{friendly_name=\"PirateWeather Temperature\",job=\"hass\"}",
     "legendFormat": "Outdoor"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rain_in{period=\"daily\"}",
     "legendFormat": "Today's Rain"
    },
    {
     "expr": "rain_in{period=\"monthly\"}",
     "legendFormat": "Monthly Rain"
    },
    {
     "expr": "delta(rain_in{period=\"monthly\"}[15m]) * 4",
     "legendFormat": "Hourly Rain Rate (15m avg)"
    }
   ]
  },
  {
   "title": "Runtime (30 day)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "sum by (action) (sum_over_time(hass_climate_action{action=\"cooling\",friendly_name=\"Main Floor Thermostat\",job=\"hass\"}[$period]))",
     "legendFormat": "Cooling"
    },
    {
     "expr": "sum by (action) (sum_over_time(hass_climate_action{action=\"heating\",friendly_name=\"Main Floor Thermostat\",job=\"hass\"}[$period]))",
     "legendFormat": "Heating"
    },
    {
     "expr": "sum by (action) (sum_over_time(hass_climate_action{action=\"drying\",friendly_name=\"Main Floor Thermostat\",job=\"hass\"}[$period]))",
     "legendFormat": "Drying"
    },
    {
     "expr": "sum(avg_over_time(hass_sensor_temperature_celsius{friendly_name=\"PirateWeather Temperature\"}[$period] * 1.8 + 32))",
     "legendFormat": "Weather"
    },
    {
     "expr": "sum by (action) (sum_over_time(hass_climate_action{action=\"fan\",friendly_name=\"Main Floor Thermostat\",job=\"hass\"}[$period]))",
     "legendFormat": "Fan"
    },
    {
     "expr": "sum by (action) (sum_over_time(hass_climate_action{action=\"preheating\",friendly_name=\"Main Floor Thermostat\",job=\"hass\"}[$period]))",
     "legendFormat": "Preheating"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "sum by (action) (sum_over_time(hass_climate_action{action=\"cooling\",friendly_name=\"Main Floor Thermostat\",job=\"hass\"}[$period]))",
     "legendFormat": "Cooling"
    },
    {
     "expr": "sum by (action) (sum_over_time(hass_climate_action{action=\"heating\",friendly_name=\"Main Floor Thermostat\",job=\"hass\"}[$period]))",
     "legendFormat": "Heating"
    },
    {
     "expr": "sum by (action) (sum_over_time(hass_climate_action{action=\"drying\",friendly_name=\"Main Floor Thermostat\",job=\"hass\"}[$period]))",
     "legendFormat": "Drying"
    },
    {
     "expr": "sum by (action) (sum_over_time(hass_climate_action{action=\"fan\",friendly_name=\"Main Floor Thermostat\",job=\"hass\"}[$period]))",
     "legendFormat": "Fan"
    },
    {
     "expr": "sum by (action) (sum_over_time(hass_climate_action{action=\"preheating\",friendly_name=\"Main Floor Thermostat\",job=\"hass\"}[$period]))",
     "legendFormat": "Preheating"
    },
    {
     "expr": "sum(avg_over_time(hass_sensor_temperature_celsius{friendly_name=\"PirateWeather Temperature\"}[1d] * 1.8 + 32))",
     "legendFormat": "Weather"
    }
   ]
  },
  {
   "title": "Runtime (30d) 1y ago",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "WITH (\n    metric = thermostat_heat_1,\n)\n-sum_over_time(metric[$period])",
     "legendFormat": "Heat 1"
    },
    {
     "expr": "WITH (\n    metric = thermostat_heat_2,\n)\n-sum_over_time(metric[$period])",
     "legendFormat": "Heat 2"
    },
    {
     "expr": "WITH (\n    metric = thermostat_aux_heat_1,\n)\n-sum_over_time(metric[$period])",
     "legendFormat": "Aux"
    },
    {
     "expr": "WITH (\n    metric = thermostat_cool_1,\n)\nsum_over_time(metric[$period])",
     "legendFormat": "Cool 1"
    },
    {
     "expr": "WITH (\n    metric = thermostat_cool_2,\n)\nsum_over_time(metric[$period])",
     "legendFormat": "Cool 2"
    },
    {
     "expr": "sum(avg_over_time(temperature{sensor=\"outdoor\"}[1d]))",
     "legendFormat": "Weather"
    }
   ]
  },
  {
   "title": "Barometer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "expr": "hass_sensor_pressure_psi{friendly_name=\"PirateWeather Pressure\",job=\"hass\"} * 68.9476",
     "legendFormat": "Barometric Pressure"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hass_sensor_humidity_percent{friendly_name=~\"Back Patio Hose Bib Crawl Space Climate Probe Humidity|Broadlink Hub Humidity|Dog Run Hose Bib Crawl Space Probe Humidity|Main Floor Thermostat Humidity|Office Closet In-Wall Climate Probe Humidity|Office Side Crawl Space Climate Probe Humidity|\",job=\"hass\"}",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "hass_sensor_humidity_percent{friendly_name=\"PirateWeather Humidity\",job=\"hass\"}",
     "legendFormat": "Outdoor"
    }
   ]
  },
  {
   "title": "Wind Speed & Gusts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "expr": "max_over_time(hass_sensor_wind_speed_mph{friendly_name=\"PirateWeather Wind Gust\",job=\"hass\"}[1m])",
     "legendFormat": "GUSTS"
    },
    {
     "expr": "max_over_time(hass_sensor_wind_speed_mph{friendly_name=\"PirateWeather Wind Speed\"}[1m])",
     "legendFormat": "SUSTAINED"
    }
   ]
  },
  {
   "title": "Solar Radiation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "expr": "hass_sensor_unit_uvu0x20index{friendly_name=\"PirateWeather UV Index\"} *.025",
     "legendFormat": "Solar Radiation"
    },
    {
     "expr": "hass_sensor_unit_uvu0x20index{friendly_name=\"PirateWeather UV Index\"}",
     "legendFormat": "Ultraviolet {{name}}"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "hass_sensor_unit_u0xb0{friendly_name=\"PirateWeather Wind Bearing\"}",
     "legendFormat": "Deerfield"
    }
   ]
  },
  {
   "title": "Setpoints and Average Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hass_climate_current_temperature_celsius{friendly_name=\"Main Floor Thermostat\",job=\"hass\"} * 1.8 + 32",
     "legendFormat": "Indoor Temperature"
    },
    {
     "expr": "hass_climate_target_temperature_celsius{friendly_name=\"Main Floor Thermostat\",job=\"hass\"} * 1.8 + 32",
     "legendFormat": "Setpoint"
    }
   ]
  }
 ]
}